// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.equisettle.foundation.domain;

import com.equisettle.foundation.domain.CaseType;
import com.equisettle.foundation.domain.CaseTypeDataOnDemand;
import com.equisettle.foundation.domain.CaseTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CaseTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CaseTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CaseTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CaseTypeIntegrationTest: @Transactional;
    
    @Autowired
    CaseTypeDataOnDemand CaseTypeIntegrationTest.dod;
    
    @Test
    public void CaseTypeIntegrationTest.testCountCaseTypes() {
        Assert.assertNotNull("Data on demand for 'CaseType' failed to initialize correctly", dod.getRandomCaseType());
        long count = CaseType.countCaseTypes();
        Assert.assertTrue("Counter for 'CaseType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CaseTypeIntegrationTest.testFindCaseType() {
        CaseType obj = dod.getRandomCaseType();
        Assert.assertNotNull("Data on demand for 'CaseType' failed to initialize correctly", obj);
        Integer id = obj.getCaseTypeId();
        Assert.assertNotNull("Data on demand for 'CaseType' failed to provide an identifier", id);
        obj = CaseType.findCaseType(id);
        Assert.assertNotNull("Find method for 'CaseType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CaseType' returned the incorrect identifier", id, obj.getCaseTypeId());
    }
    
    @Test
    public void CaseTypeIntegrationTest.testFindAllCaseTypes() {
        Assert.assertNotNull("Data on demand for 'CaseType' failed to initialize correctly", dod.getRandomCaseType());
        long count = CaseType.countCaseTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'CaseType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CaseType> result = CaseType.findAllCaseTypes();
        Assert.assertNotNull("Find all method for 'CaseType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CaseType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CaseTypeIntegrationTest.testFindCaseTypeEntries() {
        Assert.assertNotNull("Data on demand for 'CaseType' failed to initialize correctly", dod.getRandomCaseType());
        long count = CaseType.countCaseTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CaseType> result = CaseType.findCaseTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CaseType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CaseType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CaseTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CaseType' failed to initialize correctly", dod.getRandomCaseType());
        CaseType obj = dod.getNewTransientCaseType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CaseType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CaseType' identifier to be null", obj.getCaseTypeId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'CaseType' identifier to no longer be null", obj.getCaseTypeId());
    }
    
    @Test
    public void CaseTypeIntegrationTest.testRemove() {
        CaseType obj = dod.getRandomCaseType();
        Assert.assertNotNull("Data on demand for 'CaseType' failed to initialize correctly", obj);
        Integer id = obj.getCaseTypeId();
        Assert.assertNotNull("Data on demand for 'CaseType' failed to provide an identifier", id);
        obj = CaseType.findCaseType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CaseType' with identifier '" + id + "'", CaseType.findCaseType(id));
    }
    
}
