// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.equisettle.foundation.domain;

import com.equisettle.foundation.domain.CaseType;
import com.equisettle.foundation.domain.CaseTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CaseTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CaseTypeDataOnDemand: @Component;
    
    private Random CaseTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<CaseType> CaseTypeDataOnDemand.data;
    
    public CaseType CaseTypeDataOnDemand.getNewTransientCaseType(int index) {
        CaseType obj = new CaseType();
        setCaseType(obj, index);
        return obj;
    }
    
    public void CaseTypeDataOnDemand.setCaseType(CaseType obj, int index) {
        String caseType = "caseType_" + index;
        if (caseType.length() > 255) {
            caseType = caseType.substring(0, 255);
        }
        obj.setCaseType(caseType);
    }
    
    public CaseType CaseTypeDataOnDemand.getSpecificCaseType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CaseType obj = data.get(index);
        Integer id = obj.getCaseTypeId();
        return CaseType.findCaseType(id);
    }
    
    public CaseType CaseTypeDataOnDemand.getRandomCaseType() {
        init();
        CaseType obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getCaseTypeId();
        return CaseType.findCaseType(id);
    }
    
    public boolean CaseTypeDataOnDemand.modifyCaseType(CaseType obj) {
        return false;
    }
    
    public void CaseTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = CaseType.findCaseTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CaseType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CaseType>();
        for (int i = 0; i < 10; i++) {
            CaseType obj = getNewTransientCaseType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
