// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.equisettle.foundation.domain;

import com.equisettle.foundation.domain.CaseNegotiationDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CaseNegotiationDataOnDemand_Roo_Configurable {
    
    declare @type: CaseNegotiationDataOnDemand: @Configurable;
    
}
