// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.equisettle.foundation.domain;

import com.equisettle.foundation.domain.CaseNegotiation;
import com.equisettle.foundation.domain.CaseNegotiationDataOnDemand;
import com.equisettle.foundation.domain.CaseNegotiationIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CaseNegotiationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CaseNegotiationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CaseNegotiationIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CaseNegotiationIntegrationTest: @Transactional;
    
    @Autowired
    CaseNegotiationDataOnDemand CaseNegotiationIntegrationTest.dod;
    
    @Test
    public void CaseNegotiationIntegrationTest.testCountCaseNegotiations() {
        Assert.assertNotNull("Data on demand for 'CaseNegotiation' failed to initialize correctly", dod.getRandomCaseNegotiation());
        long count = CaseNegotiation.countCaseNegotiations();
        Assert.assertTrue("Counter for 'CaseNegotiation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CaseNegotiationIntegrationTest.testFindCaseNegotiation() {
        CaseNegotiation obj = dod.getRandomCaseNegotiation();
        Assert.assertNotNull("Data on demand for 'CaseNegotiation' failed to initialize correctly", obj);
        Integer id = obj.getCaseNegotiationId();
        Assert.assertNotNull("Data on demand for 'CaseNegotiation' failed to provide an identifier", id);
        obj = CaseNegotiation.findCaseNegotiation(id);
        Assert.assertNotNull("Find method for 'CaseNegotiation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CaseNegotiation' returned the incorrect identifier", id, obj.getCaseNegotiationId());
    }
    
    @Test
    public void CaseNegotiationIntegrationTest.testFindAllCaseNegotiations() {
        Assert.assertNotNull("Data on demand for 'CaseNegotiation' failed to initialize correctly", dod.getRandomCaseNegotiation());
        long count = CaseNegotiation.countCaseNegotiations();
        Assert.assertTrue("Too expensive to perform a find all test for 'CaseNegotiation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CaseNegotiation> result = CaseNegotiation.findAllCaseNegotiations();
        Assert.assertNotNull("Find all method for 'CaseNegotiation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CaseNegotiation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CaseNegotiationIntegrationTest.testFindCaseNegotiationEntries() {
        Assert.assertNotNull("Data on demand for 'CaseNegotiation' failed to initialize correctly", dod.getRandomCaseNegotiation());
        long count = CaseNegotiation.countCaseNegotiations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CaseNegotiation> result = CaseNegotiation.findCaseNegotiationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CaseNegotiation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CaseNegotiation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CaseNegotiationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CaseNegotiation' failed to initialize correctly", dod.getRandomCaseNegotiation());
        CaseNegotiation obj = dod.getNewTransientCaseNegotiation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CaseNegotiation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CaseNegotiation' identifier to be null", obj.getCaseNegotiationId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'CaseNegotiation' identifier to no longer be null", obj.getCaseNegotiationId());
    }
    
    @Test
    public void CaseNegotiationIntegrationTest.testRemove() {
        CaseNegotiation obj = dod.getRandomCaseNegotiation();
        Assert.assertNotNull("Data on demand for 'CaseNegotiation' failed to initialize correctly", obj);
        Integer id = obj.getCaseNegotiationId();
        Assert.assertNotNull("Data on demand for 'CaseNegotiation' failed to provide an identifier", id);
        obj = CaseNegotiation.findCaseNegotiation(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CaseNegotiation' with identifier '" + id + "'", CaseNegotiation.findCaseNegotiation(id));
    }
    
}
