// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.equisettle.foundation.domain;

import com.equisettle.foundation.domain.Mediator;
import com.equisettle.foundation.domain.MediatorDataOnDemand;
import com.equisettle.foundation.domain.MediatorIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MediatorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MediatorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MediatorIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MediatorIntegrationTest: @Transactional;
    
    @Autowired
    MediatorDataOnDemand MediatorIntegrationTest.dod;
    
    @Test
    public void MediatorIntegrationTest.testCountMediators() {
        Assert.assertNotNull("Data on demand for 'Mediator' failed to initialize correctly", dod.getRandomMediator());
        long count = Mediator.countMediators();
        Assert.assertTrue("Counter for 'Mediator' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MediatorIntegrationTest.testFindMediator() {
        Mediator obj = dod.getRandomMediator();
        Assert.assertNotNull("Data on demand for 'Mediator' failed to initialize correctly", obj);
        Integer id = obj.getMediatorId();
        Assert.assertNotNull("Data on demand for 'Mediator' failed to provide an identifier", id);
        obj = Mediator.findMediator(id);
        Assert.assertNotNull("Find method for 'Mediator' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Mediator' returned the incorrect identifier", id, obj.getMediatorId());
    }
    
    @Test
    public void MediatorIntegrationTest.testFindAllMediators() {
        Assert.assertNotNull("Data on demand for 'Mediator' failed to initialize correctly", dod.getRandomMediator());
        long count = Mediator.countMediators();
        Assert.assertTrue("Too expensive to perform a find all test for 'Mediator', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Mediator> result = Mediator.findAllMediators();
        Assert.assertNotNull("Find all method for 'Mediator' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Mediator' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MediatorIntegrationTest.testFindMediatorEntries() {
        Assert.assertNotNull("Data on demand for 'Mediator' failed to initialize correctly", dod.getRandomMediator());
        long count = Mediator.countMediators();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Mediator> result = Mediator.findMediatorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Mediator' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Mediator' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MediatorIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Mediator' failed to initialize correctly", dod.getRandomMediator());
        Mediator obj = dod.getNewTransientMediator(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Mediator' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Mediator' identifier to be null", obj.getMediatorId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Mediator' identifier to no longer be null", obj.getMediatorId());
    }
    
    @Test
    public void MediatorIntegrationTest.testRemove() {
        Mediator obj = dod.getRandomMediator();
        Assert.assertNotNull("Data on demand for 'Mediator' failed to initialize correctly", obj);
        Integer id = obj.getMediatorId();
        Assert.assertNotNull("Data on demand for 'Mediator' failed to provide an identifier", id);
        obj = Mediator.findMediator(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Mediator' with identifier '" + id + "'", Mediator.findMediator(id));
    }
    
}
