// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.equisettle.foundation.domain;

import com.equisettle.foundation.domain.MediatorType;
import com.equisettle.foundation.domain.MediatorTypeDataOnDemand;
import com.equisettle.foundation.domain.MediatorTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MediatorTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MediatorTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MediatorTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MediatorTypeIntegrationTest: @Transactional;
    
    @Autowired
    MediatorTypeDataOnDemand MediatorTypeIntegrationTest.dod;
    
    @Test
    public void MediatorTypeIntegrationTest.testCountMediatorTypes() {
        Assert.assertNotNull("Data on demand for 'MediatorType' failed to initialize correctly", dod.getRandomMediatorType());
        long count = MediatorType.countMediatorTypes();
        Assert.assertTrue("Counter for 'MediatorType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MediatorTypeIntegrationTest.testFindMediatorType() {
        MediatorType obj = dod.getRandomMediatorType();
        Assert.assertNotNull("Data on demand for 'MediatorType' failed to initialize correctly", obj);
        Integer id = obj.getMediatorTypeId();
        Assert.assertNotNull("Data on demand for 'MediatorType' failed to provide an identifier", id);
        obj = MediatorType.findMediatorType(id);
        Assert.assertNotNull("Find method for 'MediatorType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MediatorType' returned the incorrect identifier", id, obj.getMediatorTypeId());
    }
    
    @Test
    public void MediatorTypeIntegrationTest.testFindAllMediatorTypes() {
        Assert.assertNotNull("Data on demand for 'MediatorType' failed to initialize correctly", dod.getRandomMediatorType());
        long count = MediatorType.countMediatorTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'MediatorType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MediatorType> result = MediatorType.findAllMediatorTypes();
        Assert.assertNotNull("Find all method for 'MediatorType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MediatorType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MediatorTypeIntegrationTest.testFindMediatorTypeEntries() {
        Assert.assertNotNull("Data on demand for 'MediatorType' failed to initialize correctly", dod.getRandomMediatorType());
        long count = MediatorType.countMediatorTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MediatorType> result = MediatorType.findMediatorTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MediatorType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MediatorType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MediatorTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MediatorType' failed to initialize correctly", dod.getRandomMediatorType());
        MediatorType obj = dod.getNewTransientMediatorType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MediatorType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MediatorType' identifier to be null", obj.getMediatorTypeId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'MediatorType' identifier to no longer be null", obj.getMediatorTypeId());
    }
    
    @Test
    public void MediatorTypeIntegrationTest.testRemove() {
        MediatorType obj = dod.getRandomMediatorType();
        Assert.assertNotNull("Data on demand for 'MediatorType' failed to initialize correctly", obj);
        Integer id = obj.getMediatorTypeId();
        Assert.assertNotNull("Data on demand for 'MediatorType' failed to provide an identifier", id);
        obj = MediatorType.findMediatorType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MediatorType' with identifier '" + id + "'", MediatorType.findMediatorType(id));
    }
    
}
