package com.equisettle.ui.client.util;

public interface GeneralConstansts {
	
	Integer CASE_STATUS_CASE_INITIATED=1;
	Integer CASE_STATUS_CASE_NEGOTIATION_IN_PROGRES=2;
	Integer CASE_STATUS_OFFER_ACCEPTED=3;
	Integer CASE_STATUS_OFFER_REJECTED=4;
	Integer CASE_STATUS_CASE_IN_FINAL_OFFER_ARBITRATION=4;
	Integer CASE_STATUS_FINAL_OFFER_IS_ASSIGNED_BY_ADMIN=5;
	Integer CASE_STATUS_ESCROW_PAYMENT_INITIATED=6;
	Integer CASE_STATUS_ESCROW_PAYMENT_COMPLETED=7;
	Integer CASE_STATUS_MEDIATOR_ASSIGNED=8;
	Integer CASE_STATUS_CASE_IS_SETTLED_BY_MEDIATOR=9;
	Integer CASE_STATUS_CASE_IS_NOT_SETTLED_BY_MEDIATOR=10;
	
	Integer NEGOTIATION_STATUS_ID_INITIATED=1;
	Integer NEGOTIATION_STATUS_ID_ACCEPTED=2;
	Integer NEGOTIATION_STATUS_ID_OFFER_COUNTERED=3;

}
